# Generated by Django 4.0.5 on 2022-06-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentInfo', '0002_certform_item_lastname_item_wid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='roster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentInfo.roster'),
        ),
    ]
