# Generated by Django 4.0.5 on 2022-07-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentInfo', '0003_alter_item_complete_alter_item_roster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certform',
            name='lastName',
        ),
        migrations.AddField(
            model_name='certform',
            name='courses',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='certform',
            name='firstname',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='certform',
            name='lastname',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AlterField(
            model_name='certform',
            name='wid',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
