# Generated by Django 4.0.5 on 2022-07-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentInfo', '0004_remove_certform_lastname_certform_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='John', max_length=100)),
                ('lastname', models.CharField(default='Doe', max_length=100)),
                ('wid', models.CharField(default='0000000000', max_length=10)),
                ('courses', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
